import './globals.css'
import React from "react";
import Navbar from "@/app/common/components/home/navbars/Navbar";
import Footer from "@/app/common/components/home/footers/Footer";
// import Content from "@/app/common/components/home/contents/Content";
import Main from "@/app/common/components/Main";
// import localFonts from "next/font/local"

// const gilroy = localFonts({
//   src: 'https://fonts.cdnfonts.com/css/gilroy', //скачать файл и вставить путь.
//   weight: '700',
//   variable: '--font-gilroy',
//   display: 'swap',
// })

export const metadata = {
    title: {
        default: 'Home',
        description: 'Generated by create next app RUTEGO',
    },
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        'max-video-preview': -1,
        'max-image-preview': 'large',
        'max-snippet': -1,
      }
    },
    // icons: {
    //   chortcut: '/favicon.ico',
    // },
    //   verification: {
    //       google: 'token', теги проверок поисковой системы
    //       yandex: 'token'
    //   }
    // и так далее любые мета данные
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
        <Navbar/>
        <main className='main-h-xl flex h-[140rem]'>
            <Main/>
            {children}
        </main>
        <Footer/>
        </body>
        </html>
    )
}

